config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      put :publish
      put :unpublish
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  scope :published, -> { where(published: true) }
  
  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  
  attr_accessible :title, :summary, :body
  
  extend FriendlyId
  
  friendly_id :title, use: :slugged
  
  before_create do |article|
    article.summary = article.helpers.truncate(article.body, length: 143) unless article.summary.present?
  end
  
  def helpers
    ActionController::Base.helpers
  end
  
  def publish
    self.published = true
    self.published_at = Time.now
    save
  end
  
  def unpublish
    self.published = false
    self.published_at = nil
    save
  end
end

app/controllers/concerns/blog_controller.rb
module BlogController
  extend ActiveSupport::Concern
  
  def index
    @posts = Post
    
    if user_signed_in?
      @posts = @posts.order('created_at DESC')
    else 
      @posts = @posts.where(published: true)
      @posts = @posts.order('published_at DESC')
    end
    
    @posts = @posts.paginate(page: params[:page], per_page: 10)
    begin; @sidebar_modules = PageModule.by_collection_slug('blog-post-sidebar'); rescue ActiveRecord::RecordNotFound; nil; end
    @home_page_stylesheets = ['home_page/application', 'home_page_blog/posts']
    
    render 'posts/index', layout: 'home_page_blog/application'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include BlogController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include BlogController
  
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_resource, only: [:show, :edit, :update, :publish, :unpublish, :destroy]
  before_filter :show_breadcrumbs, only: [:new, :show, :edit]
  
  def show
    @home_page_stylesheets = ['home_page/application', 'home_page_blog/posts']
    
    render layout: 'home_page_blog/application'
  end
  
  def new
    @post = Post.new(params[:post])
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    
    if @post.save
      redirect_to @post, notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @post.update_attributes(params[:post])
      redirect_to @post, notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end
  
  def publish
    options = {}

    if @post.publish
      options[:notice] = t('posts.publish.successful')
    else  
      options[:alert] = t('posts.publish.unsuccessful')
    end
    
    redirect_to posts_path, options
  end
  
  def unpublish
    options = {}

    if @post.unpublish
      options[:notice] = t('posts.unpublish.successful')
    else  
      options[:alert] = t('posts.unpublish.unsuccessful')
    end
    
    redirect_to posts_path, options
  end

  def destroy
    @post.destroy
    
    redirect_to posts_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @post
  end
  
  private
  
  def find_resource
    @post = Post.friendly
    @post = @post.where(published: true) unless user_signed_in?
    @post = @post.find(params[:id])
  end
end

app/views/layouts/home_page_blog/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render partial: 'layouts/shared/head' %>
  </head>
  <body>
    <%= render partial: 'layouts/shared/navigation' %> 
    
    <div class="container">
      <%= render partial: 'layouts/shared/flash' %>
      
      <div class="blog-header">
<% if @show_breadcrumbs %>
        <%= breadcrumbs %><br/>
<% end %> 
        
        <h1 class="blog-title"><%= t 'general.blog.title' %></h1>
        <p class="lead blog-description"><%= t 'general.blog.sub_title' %></p>
      </div>

      <div class="row">
<% if content_for? :sidebar %>
        <div class="col-sm-8 blog-main">
          <%= yield %>
        </div>

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <%= yield :sidebar %>
        </div>
<% else %>
        <div class="col-sm-12 blog-main">
          <%= yield %>
        </div>
<% end %>
      </div>

    </div>  
    
    <%= render partial: 'layouts/shared/foot' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(
  resource, url: resource.new_record? ? posts_path : post_path(resource), 
  method: resource.new_record? ? :post : :put, wrapper: :horizontal_form,
  html: { class: 'form-horizontal', autocomplete: 'off' }
 ) do |f| %>
  <%= devise_error_messages! %>
    
  <%= f.input :title %>
  <%= f.input :summary %> 
  <%= f.input :body %>
  
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">   
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= post.title %></h2>
  <p class="blog-post-meta"><%= (post.published_at || post.created_at).strftime('%B %e, %Y') %> by <%= post.user.full_name %></p>

  <%= markdown post.body %>
  
<% if user_signed_in? %>
  <ul class="pagination">
    <li><%= link_to t('posts.edit.title'), edit_post_path(post) %></li>
  <% if post.published? %>
    <li>
      <%= link_to t('posts.unpublish.title'), unpublish_post_path(post), method: :put %>
    </li>
  <% else %>  
    <li>
      <%= link_to t('posts.publish.title'), publish_post_path(post), method: :put %>
    </li>
  <% end %>
    <li>
      <%= link_to t('general.destroy'), post_path(post), method: :delete, confirm: I18n.t('general.questions.are_you_sure') %>
    </li>
  </ul>
<% end %>
</div>

app/views/posts/_sidebar.html.erb
<% @sidebar_modules.each do |page_module| %>
  <%= render partial: page_module.partial_path %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title do %><%= t('posts.edit.title') %><% end %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if @posts.none? %>
  <p>
    <%= t('posts.index.empty_collection') %>
  </p>
<% else %>
  <%= render partial: 'posts/post', collection: @posts %>
  
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
<% end %>

<% if user_signed_in? %>
<p>
  <%= link_to new_post_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span> <%= t('posts.new.title') %>
  <% end %>
</p>
<% end %>

<% if @sidebar_modules %>
  <% content_for :sidebar do %>
    <%= render partial: 'posts/sidebar' %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<% content_for :title do %><%= t('posts.new.title') %><% end %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :title do %><%= @post.title %><% end %>

<%= render partial: 'post', locals: { post: @post } %>

app/views/posts/sidebar/_about.html.erb
<div class="sidebar-module sidebar-module-inset">
  <h4><%= t('general.blog.sidebar.about') %></h4>
  
  <%= t 'general.blog.sidebar.about_body' %>
</div>

app/views/posts/sidebar/_archive.html.erb
<div class="sidebar-module">
  <h4><%= t 'post_archive.index.title' %></h4>
  <ol class="list-unstyled">
    <li><%= t 'general.coming_soon' %>: <a href="https://github.com/home-page/home_page_blog/issues/16">Blog Issue #16</a></li>
  </ol>
</div>

app/views/posts/sidebar/_social_links.html.erb
<div class="sidebar-module">
  <h4><%= t 'general.blog.sidebar.social_links' %></h4>
  <ol class="list-unstyled">
    <li><%= t 'general.coming_soon' %>: <a href="https://github.com/home-page/home_page/issues/8">Core Issue #8</a></li>
  </ol>
</div>

app/views/posts/sidebar/_tags.html.erb
<div class="sidebar-module">
  <h4><%= t 'tags.index.title' %></h4>
  <ol class="list-unstyled">
    <li><%= t 'general.coming_soon' %>: <a href="https://github.com/home-page/home_page_blog/issues/16">Blog Issue #3</a></li>
  </ol>
</div>

app/views/settings/plugins/home_page_blog/_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="heading<%= index + 1 %>">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#settings_accordion" href="#home_page_blog_settings" aria-expanded="true" aria-controls="home_page_blog_settings">
        <%= t('settings.index.plugins.home_page_blog.index.title') %>
      </a>
    </h4>
  </div>
  
  <div id="home_page_blog_settings" class="panel-collapse collapse<% if index == 0 %> in<% end %>" role="tabpanel" aria-labelledby="heading<%= index + 1 %>">
    <div class="panel-body">
      <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#home_page_blog_settings_general" aria-controls="home_page_blog_settings_general" role="tab" data-toggle="tab">
              <%= t('settings.index.plugins.home_page.tabs.general.title') %>
            </a>
          </li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="home_page_blog_settings_general">
            <p>
              <%= setting_input(
                f, 'home_page_blog.general.partial_paths', label: t('settings.vars.home_page.general.partial_paths')
              ) %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>